Added error messages if a test fails

diff --git a/tests/test_server_lifecycle b/tests/test_server_lifecycle
--- a/tests/test_server_lifecycle
+++ b/tests/test_server_lifecycle
@@ -2,13 +2,14 @@
 
 UNINSTALL_RELEASE_AFTERWARDS=0
 
-TEXT_WITH_INSTALLED_RELEASE=`../sampctl list-releases | grep '[x] samp03xsvr_R2_patch1'`
+TEXT_WITH_INSTALLED_RELEASE=`../sampctl list-releases | grep '\[x\] samp03xsvr_R2_patch1'`
 
 if [ -z "$TEXT_WITH_INSTALLED_RELEASE" ]
 then
     ../sampctl install-release samp03xsvr_R2_patch1 > /dev/null
     if [ "$?" != 0 ]
     then
+        echo "Cannot install release samp03xsvr_R2_patch1!" >&2
         exit 1
     fi
     let "UNINSTALL_RELEASE_AFTERWARDS = 1"
@@ -18,18 +19,21 @@ TEXT_WITH_VERSION=`../sampctl list-servers | grep "^- ernie"`
 
 if [ ! -z "$TEXT_WITH_VERSION" ]
 then
+    echo "The server ernie is already installed!" >&2
     exit 1
 fi
 
 ../sampctl create-server ernie samp03xsvr_R2_patch1 45678 thisisfortestingonly > /dev/null
 if [ "$?" != 0 ]
 then
+    echo "Cannot create the server!" >&2
     exit 1
 fi
 
 ../sampctl delete-server ernie > /dev/null
 if [ "$?" != 0 ]
 then
+    echo "Cannot delete the server!" >&2
     exit 1
 fi
 
@@ -38,6 +42,7 @@ then
     ../sampctl uninstall-release samp03xsvr_R2_patch1 > /dev/null
     if [ "$?" != 0 ]
     then
+        echo "Cannot remove the release after installation!" >&2
         exit 1
     fi
 fi
diff --git a/tests/test_version_info b/tests/test_version_info
--- a/tests/test_version_info
+++ b/tests/test_version_info
@@ -4,6 +4,7 @@ TEXT_WITH_VERSION=`../sampctl --version | grep "sampctl.conf"`
 
 if [ -z "$TEXT_WITH_VERSION" ]
 then
+    echo "Cannot find sampctl.conf info in sampctl with --version command!" >&2
     exit 1
 fi
 
